// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEh4CevB3VLutwgGXh-nDrRCWvhBxT5WQ',
    appId: '1:920208595581:web:4cc2c8630b1222c8a9ef14',
    messagingSenderId: '920208595581',
    projectId: 'alllllll',
    authDomain: 'alllllll.firebaseapp.com',
    databaseURL: 'https://alllllll-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alllllll.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EJm3ELQZC5pDarHOaCsJ-V6iKGImeTg',
    appId: '1:920208595581:android:dcd7997a18259e48a9ef14',
    messagingSenderId: '920208595581',
    projectId: 'alllllll',
    databaseURL: 'https://alllllll-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alllllll.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcfmLGkvkZa1lSMQygsNstH2ZI9LjaxEY',
    appId: '1:920208595581:ios:b24d2aedb21e10bda9ef14',
    messagingSenderId: '920208595581',
    projectId: 'alllllll',
    databaseURL: 'https://alllllll-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alllllll.appspot.com',
    iosClientId: '920208595581-858ngu6ihjk7g886ferhmruj442t4lmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcfmLGkvkZa1lSMQygsNstH2ZI9LjaxEY',
    appId: '1:920208595581:ios:b24d2aedb21e10bda9ef14',
    messagingSenderId: '920208595581',
    projectId: 'alllllll',
    databaseURL: 'https://alllllll-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alllllll.appspot.com',
    iosClientId: '920208595581-858ngu6ihjk7g886ferhmruj442t4lmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
